# Generated by Django 3.0.7 on 2023-05-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebilldetails',
            name='agent',
        ),
    ]
