# Generated by Django 3.0.7 on 2023-05-08 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_salebilldetails_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebilldetails',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agentsale', to='transactions.Agent'),
            preserve_default=False,
        ),
    ]
